// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-site-content.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const key = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_ANON_KEY",
    "VITE_SUPABASE_ANON_KEY"
  ]);
  if (!key) {
    throw new Error("SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ANON_KEY) is required");
  }
  return key;
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-site-content.ts
var SECTIONS = ["about", "skills", "projects", "contact", "hero", "vision"];
var get_site_content_default = defineTool({
  name: "get_site_content",
  title: "Get site content",
  description: "Fetch the public portfolio's editable text content (hero, about, contact and other section copy), optionally filtered by section.",
  inputSchema: {
    section: z.string().optional().describe(`Optional section key to filter by, e.g. ${SECTIONS.join(", ")}.`)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ section }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("site_content").select("section,key,value");
    if (section) query = query.eq("section", section);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_skills_default = defineTool2({
  name: "list_skills",
  title: "List skills",
  description: "List Vamsi's skill categories with their proficiency level and the individual skills in each category.",
  inputSchema: {
    search: z2.string().optional().describe("Optional case-insensitive filter on the category title.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("skill_categories").select("id,title,description,proficiency,sort_order,skills(name,sort_order)").order("sort_order");
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "List projects",
  description: "List Vamsi's portfolio projects, including descriptions, tags, challenges, outcomes and demo/GitHub links.",
  inputSchema: {
    search: z3.string().optional().describe("Optional case-insensitive filter on the project title."),
    limit: z3.number().int().optional().describe("Maximum number of projects to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("projects").select("id,title,description,full_description,tags,challenges,outcome,team,demo_link,github_link,sort_order").order("sort_order").limit(Math.min(Math.max(limit ?? 50, 1), 100));
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_experience_default = defineTool4({
  name: "list_experience",
  title: "List experience and credentials",
  description: "List Vamsi's education, internships and certifications \u2014 the record of where he studied, worked and what he is certified in.",
  inputSchema: {
    kind: z4.enum(["all", "education", "internships", "certifications"]).optional().describe("Which record type to return. Defaults to all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind }) => {
    const supabase = supabaseAnon();
    const want = kind ?? "all";
    const result = {};
    if (want === "all" || want === "education") {
      const { data, error } = await supabase.from("education").select("*").order("sort_order");
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.education = data ?? [];
    }
    if (want === "all" || want === "internships") {
      const { data, error } = await supabase.from("internships").select("*").order("sort_order");
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.internships = data ?? [];
    }
    if (want === "all" || want === "certifications") {
      const { data, error } = await supabase.from("certifications").select("id,title,issuer,year,description,skills,sort_order").order("sort_order");
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.certifications = data ?? [];
    }
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-highlights.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_highlights_default = defineTool5({
  name: "list_highlights",
  title: "List ideas, achievements and goals",
  description: "List Vamsi's innovation ideas, achievements and future goals \u2014 useful for understanding his interests and direction.",
  inputSchema: {
    kind: z5.enum(["all", "ideas", "achievements", "goals"]).optional().describe("Which record type to return. Defaults to all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind }) => {
    const supabase = supabaseAnon();
    const want = kind ?? "all";
    const result = {};
    if (want === "all" || want === "ideas") {
      const { data, error } = await supabase.from("ideas").select("id,title,category,description,full_description,technologies,potential_impact,sort_order").order("sort_order");
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.ideas = data ?? [];
    }
    if (want === "all" || want === "achievements") {
      const { data, error } = await supabase.from("achievements").select("id,title,label,description,details,team,sort_order").order("sort_order");
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.achievements = data ?? [];
    }
    if (want === "all" || want === "goals") {
      const { data, error } = await supabase.from("goals").select("id,title,description,full_description,milestones,timeline,sort_order").order("sort_order");
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.goals = data ?? [];
    }
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "vamsi-s-digital-realm",
  title: "Vamsi's Digital Realm",
  version: "0.1.0",
  instructions: "Read-only tools for Vamsi's public portfolio. Use `get_site_content` for section copy, `list_skills` for skill categories, `list_projects` for projects, `list_experience` for education/internships/certifications, and `list_highlights` for ideas, achievements and goals. No private or contact-message data is exposed.",
  tools: [
    get_site_content_default,
    list_skills_default,
    list_projects_default,
    list_experience_default,
    list_highlights_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
